#!/usr/bin/env python3
"""
yakugo_build_manual_seeds.py
============================
Generates yakugo_manual_seeds.json — a curated set of ~450 high-quality
English→Hebrew word pairs covering nouns, verbs, adjectives, and adverbs.

Hebrew targets use the normalized (non-final-letter) form so crossword
intersections work regardless of where in the word the shared letter falls.
Final letter normalization:  ך→כ  ם→מ  ן→נ  ף→פ  ץ→צ

Run once to (re-)generate the seed file:
  python yakugo_build_manual_seeds.py

Then merge into the main wordlist:
  python yakugo_merge_seeds.py
"""

import json, os, sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

_HERE = os.path.dirname(__file__)
OUT = os.path.join(_HERE, "yakugo_manual_seeds.json")

# ---------------------------------------------------------------------------
# Raw data: (english, hebrew_normalized)
# Hebrew lengths 2–8 only; single-char not useful for crosswords.
# Final letters already converted: ך→כ, ם→מ, ן→נ, ף→פ, ץ→צ
# ---------------------------------------------------------------------------

NOUNS = [
    # Body parts
    ("head",         "ראש"),
    ("hand",         "יד"),
    ("foot",         "רגל"),
    ("eye",          "עינ"),
    ("ear",          "אוזנ"),
    ("nose",         "אפ"),
    ("mouth",        "פה"),
    ("hair",         "שיער"),
    ("heart",        "לב"),
    ("stomach",      "בטנ"),
    ("back",         "גב"),
    ("arm",          "זרוע"),
    ("finger",       "אצבע"),
    ("tooth",        "שנ"),
    ("tongue",       "לשונ"),
    ("face",         "פנימ"),
    ("knee",         "ברכ"),
    ("shoulder",     "כתפ"),
    ("leg",          "רגל"),
    ("nail",         "ציפורנ"),
    ("skin",         "עור"),
    ("bone",         "עצמ"),
    ("blood",        "דמ"),
    ("brain",        "מוח"),
    ("throat",       "גרונ"),
    ("chest",        "חזה"),
    ("lip",          "שפה"),
    ("heel",         "עקב"),
    ("thumb",        "בוהנ"),
    # Animals
    ("horse",        "סוס"),
    ("cow",          "פרה"),
    ("sheep",        "כבש"),
    ("goat",         "עז"),
    ("rabbit",       "ארנב"),
    ("fish",         "דג"),
    ("bird",         "ציפור"),
    ("chicken",      "תרנגול"),
    ("lion",         "אריה"),
    ("bear",         "דוב"),
    ("wolf",         "זאב"),
    ("fox",          "שועל"),
    ("elephant",     "פיל"),
    ("monkey",       "קוף"),
    ("snake",        "נחש"),
    ("mouse",        "עכבר"),
    ("frog",         "צפרדע"),
    ("bee",          "דבורה"),
    ("fly",          "זבוב"),
    ("ant",          "נמלה"),
    ("eagle",        "נשר"),
    ("dove",         "יונה"),
    ("pig",          "חזיר"),
    ("camel",        "גמל"),
    ("donkey",       "חמור"),
    ("butterfly",    "פרפר"),
    ("turtle",       "צב"),
    ("deer",         "איל"),
    ("giraffe",      "ג'ירפה"),
    # Food & drink
    ("egg",          "ביצה"),
    ("meat",         "בשר"),
    ("rice",         "אורז"),
    ("soup",         "מרק"),
    ("salad",        "סלט"),
    ("fruit",        "פרי"),
    ("vegetable",    "ירק"),
    ("apple",        "תפוח"),
    ("banana",       "בננה"),
    ("orange",       "תפוז"),
    ("lemon",        "לימונ"),
    ("strawberry",   "תות"),
    ("grapes",       "ענב"),
    ("olive",        "זית"),
    ("onion",        "בצל"),
    ("coffee",       "קפה"),
    ("juice",        "מיצ"),
    ("wine",         "יינ"),
    ("beer",         "בירה"),
    ("cake",         "עוגה"),
    ("cheese",       "גבינה"),
    ("butter",       "חמאה"),
    ("sugar",        "סוכר"),
    ("salt",         "מלח"),
    ("oil",          "שמנ"),
    ("honey",        "דבש"),
    ("garlic",       "שומ"),
    ("pepper",       "פלפל"),
    ("tomato",       "עגבניה"),
    ("potato",       "תפוח אדמה"),
    # Places
    ("city",         "עיר"),
    ("village",      "כפר"),
    ("country",      "מדינה"),
    ("sea",          "ימ"),
    ("river",        "נהר"),
    ("mountain",     "הר"),
    ("forest",       "יער"),
    ("desert",       "מדבר"),
    ("street",       "רחוב"),
    ("park",         "פארק"),
    ("market",       "שוק"),
    ("field",        "שדה"),
    ("beach",        "חופ"),
    ("bridge",       "גשר"),
    ("cave",         "מערה"),
    ("island",       "אי"),
    ("valley",       "עמק"),
    ("lake",         "אגמ"),
    ("port",         "נמל"),
    ("airport",      "נמל תעופה"),
    ("hotel",        "מלונ"),
    ("restaurant",   "מסעדה"),
    ("store",        "חנות"),
    ("bank",         "בנק"),
    ("office",       "משרד"),
    ("factory",      "מפעל"),
    ("museum",       "מוזיאונ"),
    ("library",      "ספריה"),
    ("garden",       "גנ"),
    ("roof",         "גג"),
    # Nature
    ("sun",          "שמש"),
    ("cloud",        "עננ"),
    ("rain",         "גשמ"),
    ("snow",         "שלג"),
    ("wind",         "רוח"),
    ("fire",         "אש"),
    ("earth",        "אדמה"),
    ("sand",         "חול"),
    ("grass",        "דשא"),
    ("leaf",         "עלה"),
    ("seed",         "זרע"),
    ("root",         "שורש"),
    ("branch",       "ענפ"),
    ("wave",         "גל"),
    ("sky",          "שמימ"),
    ("storm",        "סערה"),
    ("thunder",      "רעמ"),
    ("lightning",    "ברק"),
    ("rainbow",      "קשת"),
    ("shadow",       "צל"),
    # Time
    ("night",        "לילה"),
    ("minute",       "דקה"),
    ("second",       "שניה"),
    ("week",         "שבוע"),
    ("month",        "חודש"),
    ("today",        "היומ"),
    ("spring",       "אביב"),
    ("summer",       "קיצ"),
    ("autumn",       "סתיו"),
    ("winter",       "חורפ"),
    ("birthday",     "יומ הולדת"),
    ("holiday",      "חג"),
    ("weekend",      "סוף שבוע"),
    # Family
    ("mother",       "אמ"),
    ("son",          "בנ"),
    ("daughter",     "בת"),
    ("sister",       "אחות"),
    ("grandfather",  "סבא"),
    ("grandmother",  "סבתא"),
    ("uncle",        "דוד"),
    ("aunt",         "דודה"),
    ("husband",      "בעל"),
    ("wife",         "אישה"),
    ("baby",         "תינוק"),
    ("girl",         "ילדה"),
    ("family",       "משפחה"),
    ("couple",       "זוג"),
    ("neighbor",     "שכנ"),
    ("friend",       "חבר"),
    ("enemy",        "אויב"),
    ("guest",        "אורח"),
    # Home & furniture
    ("window",       "חלונ"),
    ("wall",         "קיר"),
    ("floor",        "רצפה"),
    ("ceiling",      "תקרה"),
    ("table",        "שולחנ"),
    ("bed",          "מיטה"),
    ("sofa",         "ספה"),
    ("lamp",         "מנורה"),
    ("clock",        "שעונ"),
    ("phone",        "טלפונ"),
    ("computer",     "מחשב"),
    ("television",   "טלוויזיה"),
    ("key",          "מפתח"),
    ("mirror",       "מראה"),
    ("cupboard",     "ארונ"),
    ("shelf",        "מדפ"),
    ("carpet",       "שטיח"),
    ("kitchen",      "מטבח"),
    ("room",         "חדר"),
    ("stairs",       "מדרגות"),
    ("gate",         "שער"),
    ("fence",        "גדר"),
    ("roof",         "גג"),
    ("garden",       "גנ"),
    # Clothing
    ("shirt",        "חולצה"),
    ("pants",        "מכנסימ"),
    ("dress",        "שמלה"),
    ("shoe",         "נעל"),
    ("sock",         "גרב"),
    ("hat",          "כובע"),
    ("jacket",       "מעיל"),
    ("glove",        "כפפה"),
    ("scarf",        "צעיפ"),
    ("belt",         "חגורה"),
    ("coat",         "מעיל"),
    ("tie",          "עניבה"),
    ("umbrella",     "מטריה"),
    ("glasses",      "משקפימ"),
    ("pocket",       "כיס"),
    ("button",       "כפתור"),
    ("zipper",       "רוכסנ"),
    # Colors
    ("color",        "צבע"),
    ("red",          "אדומ"),
    ("blue",         "כחול"),
    ("green",        "ירוק"),
    ("yellow",       "צהוב"),
    ("white",        "לבנ"),
    ("black",        "שחור"),
    ("orange",       "כתומ"),
    ("purple",       "סגול"),
    ("pink",         "ורוד"),
    ("brown",        "חומ"),
    ("gray",         "אפור"),
    # Transport
    ("car",          "מכונית"),
    ("bus",          "אוטובוס"),
    ("train",        "רכבת"),
    ("plane",        "מטוס"),
    ("ship",         "ספינה"),
    ("boat",         "סירה"),
    ("bicycle",      "אופניימ"),
    ("taxi",         "מונית"),
    ("truck",        "משאית"),
    ("motorcycle",   "אופנוע"),
    ("road",         "כביש"),
    # School / work
    ("teacher",      "מורה"),
    ("student",      "תלמיד"),
    ("lesson",       "שיעור"),
    ("homework",     "שיעורי בית"),
    ("exam",         "מבחנ"),
    ("pen",          "עט"),
    ("pencil",       "עיפרונ"),
    ("notebook",     "מחברת"),
    ("bag",          "תיק"),
    ("paper",        "נייר"),
    ("class",        "כיתה"),
    ("doctor",       "רופא"),
    ("nurse",        "אחות"),
    ("lawyer",       "עורכ דינ"),
    ("engineer",     "מהנדס"),
    ("soldier",      "חייל"),
    ("police",       "שוטר"),
    ("firefighter",  "כבאי"),
    ("chef",         "שף"),
    ("artist",       "אמנ"),
    ("musician",     "מוזיקאי"),
    ("actor",        "שחקנ"),
    ("writer",       "סופר"),
    ("scientist",    "מדעינ"),
    # General common nouns
    ("name",         "שמ"),
    ("word",         "מילה"),
    ("sentence",     "משפט"),
    ("story",        "סיפור"),
    ("question",     "שאלה"),
    ("answer",       "תשובה"),
    ("problem",      "בעיה"),
    ("idea",         "רעיונ"),
    ("plan",         "תכניות"),
    ("dream",        "חלומ"),
    ("memory",       "זיכרונ"),
    ("hope",         "תקווה"),
    ("fear",         "פחד"),
    ("anger",        "כעס"),
    ("joy",          "שמחה"),
    ("sadness",      "עצבות"),
    ("surprise",     "הפתעה"),
    ("truth",        "אמת"),
    ("lie",          "שקר"),
    ("secret",       "סוד"),
    ("gift",         "מתנה"),
    ("price",        "מחיר"),
    ("money",        "כספ"),
    ("work",         "עבודה"),
    ("game",         "משחק"),
    ("sport",        "ספורט"),
    ("music",        "מוזיקה"),
    ("art",          "אמנות"),
    ("language",     "שפה"),
    ("culture",      "תרבות"),
    ("nature",       "טבע"),
    ("world",        "עולמ"),
    ("life",         "חיימ"),
    ("death",        "מוות"),
    ("health",       "בריאות"),
    ("power",        "כוח"),
    ("war",          "מלחמה"),
    ("peace",        "שלומ"),
    ("freedom",      "חירות"),
    ("law",          "חוק"),
    ("government",   "ממשלה"),
    ("society",      "חברה"),
    ("future",       "עתיד"),
    ("past",         "עבר"),
    ("present",      "הווה"),
    ("change",       "שינוי"),
    ("beginning",    "התחלה"),
    ("end",          "סופ"),
    ("number",       "מספר"),
    ("letter",       "אות"),
    ("sign",         "שלט"),
    ("map",          "מפה"),
    ("photograph",   "תצלומ"),
    ("news",         "חדשות"),
    ("radio",        "רדיו"),
    ("internet",     "אינטרנט"),
    ("message",      "הודעה"),
    ("meeting",      "פגישה"),
    ("party",        "מסיבה"),
    ("wedding",      "חתונה"),
    ("journey",      "מסע"),
    ("adventure",    "הרפתקה"),
    ("reward",       "פרס"),
    ("mistake",      "טעות"),
    ("luck",         "מזל"),
    ("choice",       "בחירה"),
    ("responsibility","אחריות"),
    ("success",      "הצלחה"),
    ("failure",      "כישלונ"),
]

VERBS = [
    ("to eat",       "לאכול"),
    ("to drink",     "לשתות"),
    ("to sleep",     "לישונ"),
    ("to walk",      "ללכת"),
    ("to run",       "לרוצ"),
    ("to speak",     "לדבר"),
    ("to read",      "לקרוא"),
    ("to write",     "לכתוב"),
    ("to see",       "לראות"),
    ("to hear",      "לשמוע"),
    ("to think",     "לחשוב"),
    ("to know",      "לדעת"),
    ("to love",      "לאהוב"),
    ("to want",      "לרצות"),
    ("to help",      "לעזור"),
    ("to work",      "לעבוד"),
    ("to play",      "לשחק"),
    ("to laugh",     "לצחוק"),
    ("to cry",       "לבכות"),
    ("to give",      "לתת"),
    ("to take",      "לקחת"),
    ("to buy",       "לקנות"),
    ("to sell",      "למכור"),
    ("to open",      "לפתוח"),
    ("to close",     "לסגור"),
    ("to come",      "לבוא"),
    ("to sit",       "לשבת"),
    ("to stand",     "לעמוד"),
    ("to learn",     "ללמוד"),
    ("to teach",     "ללמד"),
    ("to remember",  "לזכור"),
    ("to forget",    "לשכוח"),
    ("to find",      "למצוא"),
    ("to lose",      "לאבד"),
    ("to build",     "לבנות"),
    ("to break",     "לשבור"),
    ("to cook",      "לבשל"),
    ("to wash",      "לרחוצ"),
    ("to clean",     "לנקות"),
    ("to travel",    "לטייל"),
    ("to meet",      "להיפגש"),
    ("to start",     "להתחיל"),
    ("to finish",    "לסיימ"),
    ("to try",       "לנסות"),
    ("to ask",       "לשאול"),
    ("to answer",    "לענות"),
    ("to listen",    "להקשיב"),
    ("to sing",      "לשיר"),
    ("to dance",     "לרקוד"),
    ("to draw",      "לצייר"),
    ("to swim",      "לשחות"),
    ("to fly",       "לעוף"),
    ("to drive",     "לנהוג"),
    ("to wait",      "לחכות"),
    ("to change",    "לשנות"),
    ("to choose",    "לבחור"),
    ("to fall",      "ליפול"),
    ("to rise",      "לעלות"),
    ("to push",      "לדחופ"),
    ("to pull",      "למשוכ"),
    ("to throw",     "לזרוק"),
    ("to catch",     "לתפוס"),
    ("to jump",      "לקפוצ"),
    ("to climb",     "לטפס"),
    ("to enter",     "להיכנס"),
    ("to exit",      "לצאת"),
    ("to send",      "לשלוח"),
    ("to receive",   "לקבל"),
    ("to pay",       "לשלמ"),
    ("to borrow",    "ללוות"),
    ("to lend",      "להלוות"),
    ("to save",      "לשמור"),
    ("to lose",      "להפסיד"),
    ("to win",       "לנצח"),
    ("to fight",     "להילחמ"),
    ("to protect",   "להגנ"),
    ("to share",     "לשתפ"),
    ("to connect",   "לחבר"),
    ("to separate",  "להפריד"),
    ("to plan",      "לתכנ"),
    ("to create",    "ליצור"),
    ("to destroy",   "להרוס"),
    ("to fix",       "לתקנ"),
    ("to hide",      "להסתיר"),
    ("to show",      "להראות"),
    ("to feel",      "להרגיש"),
    ("to smell",     "להריח"),
    ("to touch",     "לגעת"),
    ("to taste",     "לטעומ"),
    ("to explain",   "להסביר"),
    ("to understand","להבינ"),
    ("to believe",   "להאמינ"),
    ("to promise",   "להבטיח"),
    ("to agree",     "להסכימ"),
    ("to refuse",    "לסרב"),
    ("to accept",    "לקבל"),
    ("to invite",    "להזמינ"),
    ("to visit",     "לבקר"),
    ("to celebrate", "לחגוג"),
    ("to pray",      "להתפלל"),
    ("to dream",     "לחלומ"),
    ("to live",      "לחיות"),
    ("to die",       "למות"),
    ("to grow",      "לגדל"),
    ("to shrink",    "להתכווצ"),
    ("to happen",    "לקרות"),
    ("to stop",      "לעצור"),
    ("to continue",  "להמשיכ"),
    ("to return",    "לחזור"),
    ("to leave",     "לעזוב"),
    ("to arrive",    "להגיע"),
]

ADJECTIVES = [
    ("good",         "טוב"),
    ("bad",          "רע"),
    ("big",          "גדול"),
    ("small",        "קטנ"),
    ("long",         "ארוכ"),
    ("short",        "קצר"),
    ("new",          "חדש"),
    ("old",          "ישנ"),
    ("beautiful",    "יפה"),
    ("ugly",         "מכוער"),
    ("fast",         "מהיר"),
    ("slow",         "איטי"),
    ("hot",          "חמ"),
    ("cold",         "קר"),
    ("happy",        "שמח"),
    ("sad",          "עצוב"),
    ("hungry",       "רעב"),
    ("tired",        "עייפ"),
    ("strong",       "חזק"),
    ("weak",         "חלש"),
    ("smart",        "חכמ"),
    ("stupid",       "טיפש"),
    ("brave",        "אמיצ"),
    ("scared",       "מפוחד"),
    ("clean",        "נקי"),
    ("dirty",        "מלוכלכ"),
    ("rich",         "עשיר"),
    ("poor",         "עני"),
    ("young",        "צעיר"),
    ("easy",         "קל"),
    ("hard",         "קשה"),
    ("simple",       "פשוט"),
    ("complex",      "מסובכ"),
    ("empty",        "ריק"),
    ("full",         "מלא"),
    ("open",         "פתוח"),
    ("closed",       "סגור"),
    ("true",         "אמיתי"),
    ("false",        "שקרי"),
    ("sweet",        "מתוק"),
    ("sour",         "חמוצ"),
    ("salty",        "מלוח"),
    ("expensive",    "יקר"),
    ("cheap",        "זול"),
    ("funny",        "מצחיק"),
    ("serious",      "רציני"),
    ("quiet",        "שקט"),
    ("loud",         "רועש"),
    ("dark",         "חשוכ"),
    ("bright",       "בהיר"),
    ("sick",         "חולה"),
    ("healthy",      "בריא"),
    ("important",    "חשוב"),
    ("interesting",  "מעניינ"),
    ("boring",       "משעממ"),
    ("kind",         "אדיב"),
    ("cruel",        "אכזרי"),
    ("honest",       "ישר"),
    ("lazy",         "עצלנ"),
    ("active",       "פעיל"),
    ("careful",      "זהיר"),
    ("wild",         "פרוע"),
    ("gentle",       "עדינ"),
    ("sharp",        "חד"),
    ("soft",         "רכ"),
    ("hard",         "קשה"),
    ("smooth",       "חלק"),
    ("rough",        "מחוספס"),
    ("thin",         "דק"),
    ("thick",        "עבה"),
    ("wide",         "רחב"),
    ("narrow",       "צר"),
    ("deep",         "עמוק"),
    ("shallow",      "רדוד"),
    ("heavy",        "כבד"),
    ("light",        "קל"),
    ("wet",          "רטוב"),
    ("dry",          "יבש"),
    ("fresh",        "טרי"),
    ("rotten",       "רקוב"),
    ("alive",        "חי"),
    ("famous",       "מפורסמ"),
    ("strange",      "מוזר"),
    ("normal",       "רגיל"),
    ("special",      "מיוחד"),
    ("free",         "חופשי"),
    ("busy",         "עסוק"),
    ("ready",        "מוכנ"),
    ("lost",         "אבוד"),
    ("safe",         "בטוח"),
    ("dangerous",    "מסוכנ"),
    ("possible",     "אפשרי"),
    ("impossible",   "בלתי אפשרי"),
    ("necessary",    "הכרחי"),
    ("sufficient",   "מספיק"),
    ("similar",      "דומה"),
    ("different",    "שונה"),
]

ADVERBS = [
    ("here",         "כאנ"),
    ("there",        "שמ"),
    ("now",          "עכשיו"),
    ("soon",         "בקרוב"),
    ("already",      "כבר"),
    ("still",        "עדיינ"),
    ("again",        "שוב"),
    ("also",         "גמ"),
    ("very",         "מאוד"),
    ("a lot",        "הרבה"),
    ("a little",     "קצת"),
    ("slowly",       "לאט"),
    ("quickly",      "מהר"),
    ("together",     "יחד"),
    ("alone",        "לבד"),
    ("perhaps",      "אולי"),
    ("really",       "באמת"),
    ("almost",       "כמעט"),
    ("exactly",      "בדיוק"),
    ("enough",       "מספיק"),
    ("therefore",    "לכנ"),
    ("yesterday",    "אתמול"),
    ("tomorrow",     "מחר"),
    ("tonight",      "הלילה"),
    ("outside",      "בחוצ"),
    ("inside",       "בפנימ"),
    ("above",        "למעלה"),
    ("below",        "למטה"),
    ("before",       "לפני"),
    ("after",        "אחרי"),
    ("always",       "תמיד"),
    ("sometimes",    "לפעמימ"),
    ("finally",      "לבסוף"),
    ("immediately",  "מיד"),
    ("usually",      "בדרכ כלל"),
    ("rarely",       "לעיתימ רחוקות"),
    ("too",          "גמ כנ"),
    ("so",           "כלכ"),
    ("just",         "רק"),
    ("first",        "ראשונ"),
    ("then",         "אזי"),
    ("everywhere",   "בכל מקומ"),
    ("nowhere",      "באפ מקומ"),
    ("forward",      "קדימה"),
    ("backward",     "אחורה"),
    ("upward",       "למעלה"),
    ("downward",     "למטה"),
    ("right",        "ימינה"),
    ("left",         "שמאלה"),
    ("truly",        "באמת"),
    ("clearly",      "בבירור"),
    ("certainly",    "בהחלט"),
    ("probably",     "כנראה"),
    ("hopefully",    "בתקווה"),
    ("suddenly",     "פתאומ"),
    ("slowly",       "לאט לאט"),
]


def build() -> None:
    _FINAL = str.maketrans("ךםןףץ", "כמנפצ")
    def norm(s: str) -> str:
        return s.translate(_FINAL)

    def make_entry(src: str, tgt: str) -> dict:
        return {"Source": src, "Target": norm(tgt)}

    categories = {
        "noun":      [make_entry(s, t) for s, t in NOUNS],
        "verb":      [make_entry(s, t) for s, t in VERBS],
        "adjective": [make_entry(s, t) for s, t in ADJECTIVES],
        "adverb":    [make_entry(s, t) for s, t in ADVERBS],
    }

    total = sum(len(v) for v in categories.values())
    data = {
        "SourceLanguage": "en",
        "TargetLanguage": "he",
        "Categories": categories,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Written {total} seeds → {os.path.abspath(OUT)}")
    for cat, entries in categories.items():
        print(f"  {cat:12s}: {len(entries)} words")


if __name__ == "__main__":
    build()
